## This is test deployment for Kubernetes platforms.
## This is _not_ intended to be use in producction.
##
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-pushgateway
  name: test-pushgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-pushgateway
  template:
    metadata:
      labels:
        app: test-pushgateway
    spec:
      containers:
      - image: bitnami/pushgateway
        name: pushgateway
